return {
	-- "folke/noice.nvim",
	-- event = "VeryLazy",
	-- config = function()
	-- 	require("noice").setup({
	-- 		lsp = {
	-- 			override = {
	-- 				["vim.lsp.util.convert_input_to_markdown_lines"] = true,
	-- 				["vim.lsp.util.stylize_markdown"] = true,
	-- 				["cmp.entry.get_documentation"] = true,
	-- 			},
	-- 		},
	-- 		presets = {
	-- 			lsp_doc_border = true,
	-- 			bottom_search = true,
	-- 			command_palette = false,
	-- 			long_message_to_split = true,
	-- 			inc_rename = false,
	-- 		},
	-- 		routes = {
	-- 			{
	-- 				view = "notify",
	-- 				filter = { event = "msg_showmode" },
	-- 			},
	-- 			{
	-- 				filter = {
	-- 					event = "msg_show",
	-- 					kind = "",
	-- 					find = "written",
	-- 				},
	-- 				opts = { skip = true },
	-- 			},
	-- 		},
	-- 	})
	-- end,
	-- dependencies = {
	-- 	-- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
	-- 	"MunifTanjim/nui.nvim",
	-- 	-- OPTIONAL:
	-- 	--   `nvim-notify` is only needed, if you want to use the notification view.
	-- 	--   If not available, we use `mini` as the fallback
	-- 	-- {
	-- 	--   "rcarriga/nvim-notify",
	-- 	--   opts = {
	-- 	--     timeout = 5000,
	-- 	--     render = "minimal",
	-- 	--     stages = "slide",
	-- 	--   },
	-- 	-- },
	-- },
}
